export * from "./home";
export * from "./hero";
export * from "./WhyThisMatters";
export * from "./AboutAuthor";
export * from "./Resourcessection";
export * from "./WhyThisMatters";
export * from "./Gallery";
export * from "./Footer";
export * from "./Freeprintable";